/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Post = IDL.Record({
  'id' : IDL.Nat,
  'isDeleted' : IDL.Bool,
  'content' : IDL.Text,
  'hashtags' : IDL.Vec(IDL.Text),
  'imageUrls' : IDL.Vec(IDL.Text),
  'authorId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'isReel' : IDL.Bool,
  'commentsCount' : IDL.Nat,
  'likesCount' : IDL.Nat,
  'videoUrl' : IDL.Text,
  'scheduledAt' : IDL.Opt(IDL.Int),
});
export const AdminStats = IDL.Record({
  'bannedUsers' : IDL.Nat,
  'totalReports' : IDL.Nat,
  'activeConversations' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalPosts' : IDL.Nat,
  'totalComments' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'socialLinks' : IDL.Vec(IDL.Text),
  'followersCount' : IDL.Nat,
  'createdAt' : IDL.Int,
  'avatarUrl' : IDL.Text,
  'isBanned' : IDL.Bool,
  'isAdmin' : IDL.Bool,
  'followingCount' : IDL.Nat,
  'coverUrl' : IDL.Text,
  'skills' : IDL.Vec(IDL.Text),
  'postsCount' : IDL.Nat,
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'isDeleted' : IDL.Bool,
  'content' : IDL.Text,
  'authorId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'likesCount' : IDL.Nat,
  'postId' : IDL.Nat,
});
export const Conversation = IDL.Record({
  'id' : IDL.Nat,
  'participants' : IDL.Vec(IDL.Principal),
  'lastMessageAt' : IDL.Int,
  'isGroup' : IDL.Bool,
  'createdAt' : IDL.Int,
  'lastMessage' : IDL.Text,
  'groupName' : IDL.Text,
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'isRead' : IDL.Bool,
  'conversationId' : IDL.Nat,
  'senderId' : IDL.Principal,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'notifType' : IDL.Text,
  'createdAt' : IDL.Int,
  'isRead' : IDL.Bool,
  'actorId' : IDL.Principal,
  'entityId' : IDL.Text,
  'recipientId' : IDL.Principal,
});

export const idlService = IDL.Service({
  'addComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'adminDeletePost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'banUser' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'chatWithAI' : IDL.Func(
      [
        IDL.Text,
        IDL.Vec(IDL.Record({ 'content' : IDL.Text, 'role' : IDL.Text })),
      ],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'clearMyOpenAIApiKey' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'createConversation' : IDL.Func(
      [IDL.Vec(IDL.Principal), IDL.Bool, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createPost' : IDL.Func(
      [
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Bool,
        IDL.Opt(IDL.Int),
      ],
      [IDL.Nat],
      [],
    ),
  'deleteComment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deletePost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'followUser' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'generateCaption' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'getAdminPosts' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Post)], ['query']),
  'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
  'getAdminUsers' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
  'getExplorePosts' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Post)], ['query']),
  'getFeedPosts' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Post)], ['query']),
  'getFollowers' : IDL.Func([IDL.Principal], [IDL.Vec(UserProfile)], ['query']),
  'getFollowing' : IDL.Func([IDL.Principal], [IDL.Vec(UserProfile)], ['query']),
  'getMessages' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
  'getReels' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Post)], ['query']),
  'getSavedPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getSuggestedUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getTrendingHashtags' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserPosts' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Nat],
      [IDL.Vec(Post)],
      ['query'],
    ),
  'isFollowingUser' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isMyOpenAIConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'isPostLiked' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'likeComment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'likePost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'markAllNotificationsRead' : IDL.Func([], [], []),
  'markMessageRead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'markNotificationRead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'reportContent' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'savePost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], ['query']),
  'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'setMyOpenAIApiKey' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'suggestHashtags' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(IDL.Text), 'err' : IDL.Text })],
      [],
    ),
  'unbanUser' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'unfollowUser' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'unlikePost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'unsavePost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'updateProfile' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
      ],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'isDeleted' : IDL.Bool,
    'content' : IDL.Text,
    'hashtags' : IDL.Vec(IDL.Text),
    'imageUrls' : IDL.Vec(IDL.Text),
    'authorId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'isReel' : IDL.Bool,
    'commentsCount' : IDL.Nat,
    'likesCount' : IDL.Nat,
    'videoUrl' : IDL.Text,
    'scheduledAt' : IDL.Opt(IDL.Int),
  });
  const AdminStats = IDL.Record({
    'bannedUsers' : IDL.Nat,
    'totalReports' : IDL.Nat,
    'activeConversations' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalPosts' : IDL.Nat,
    'totalComments' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'socialLinks' : IDL.Vec(IDL.Text),
    'followersCount' : IDL.Nat,
    'createdAt' : IDL.Int,
    'avatarUrl' : IDL.Text,
    'isBanned' : IDL.Bool,
    'isAdmin' : IDL.Bool,
    'followingCount' : IDL.Nat,
    'coverUrl' : IDL.Text,
    'skills' : IDL.Vec(IDL.Text),
    'postsCount' : IDL.Nat,
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'isDeleted' : IDL.Bool,
    'content' : IDL.Text,
    'authorId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'likesCount' : IDL.Nat,
    'postId' : IDL.Nat,
  });
  const Conversation = IDL.Record({
    'id' : IDL.Nat,
    'participants' : IDL.Vec(IDL.Principal),
    'lastMessageAt' : IDL.Int,
    'isGroup' : IDL.Bool,
    'createdAt' : IDL.Int,
    'lastMessage' : IDL.Text,
    'groupName' : IDL.Text,
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'isRead' : IDL.Bool,
    'conversationId' : IDL.Nat,
    'senderId' : IDL.Principal,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'notifType' : IDL.Text,
    'createdAt' : IDL.Int,
    'isRead' : IDL.Bool,
    'actorId' : IDL.Principal,
    'entityId' : IDL.Text,
    'recipientId' : IDL.Principal,
  });
  
  return IDL.Service({
    'addComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'adminDeletePost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'banUser' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'chatWithAI' : IDL.Func(
        [
          IDL.Text,
          IDL.Vec(IDL.Record({ 'content' : IDL.Text, 'role' : IDL.Text })),
        ],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'clearMyOpenAIApiKey' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'createConversation' : IDL.Func(
        [IDL.Vec(IDL.Principal), IDL.Bool, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createPost' : IDL.Func(
        [
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Bool,
          IDL.Opt(IDL.Int),
        ],
        [IDL.Nat],
        [],
      ),
    'deleteComment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deletePost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'followUser' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'generateCaption' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'getAdminPosts' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Post)], ['query']),
    'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
    'getAdminUsers' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'getConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
    'getExplorePosts' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Post)],
        ['query'],
      ),
    'getFeedPosts' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Post)], ['query']),
    'getFollowers' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'getFollowing' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'getMessages' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
    'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
    'getReels' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Post)], ['query']),
    'getSavedPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getSuggestedUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getTrendingHashtags' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserPosts' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Nat],
        [IDL.Vec(Post)],
        ['query'],
      ),
    'isFollowingUser' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isMyOpenAIConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'isPostLiked' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'likeComment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'likePost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'markAllNotificationsRead' : IDL.Func([], [], []),
    'markMessageRead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'markNotificationRead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'reportContent' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'savePost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], ['query']),
    'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'setMyOpenAIApiKey' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'suggestHashtags' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(IDL.Text), 'err' : IDL.Text })],
        [],
      ),
    'unbanUser' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'unfollowUser' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'unlikePost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'unsavePost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'updateProfile' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
        ],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };