/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminStats {
  'bannedUsers' : bigint,
  'totalReports' : bigint,
  'activeConversations' : bigint,
  'totalUsers' : bigint,
  'totalPosts' : bigint,
  'totalComments' : bigint,
}
export interface Comment {
  'id' : bigint,
  'isDeleted' : boolean,
  'content' : string,
  'authorId' : Principal,
  'createdAt' : bigint,
  'likesCount' : bigint,
  'postId' : bigint,
}
export interface Conversation {
  'id' : bigint,
  'participants' : Array<Principal>,
  'lastMessageAt' : bigint,
  'isGroup' : boolean,
  'createdAt' : bigint,
  'lastMessage' : string,
  'groupName' : string,
}
export interface Message {
  'id' : bigint,
  'content' : string,
  'createdAt' : bigint,
  'isRead' : boolean,
  'conversationId' : bigint,
  'senderId' : Principal,
}
export interface Notification {
  'id' : bigint,
  'notifType' : string,
  'createdAt' : bigint,
  'isRead' : boolean,
  'actorId' : Principal,
  'entityId' : string,
  'recipientId' : Principal,
}
export interface Post {
  'id' : bigint,
  'isDeleted' : boolean,
  'content' : string,
  'hashtags' : Array<string>,
  'imageUrls' : Array<string>,
  'authorId' : Principal,
  'createdAt' : bigint,
  'isReel' : boolean,
  'commentsCount' : bigint,
  'likesCount' : bigint,
  'videoUrl' : string,
  'scheduledAt' : [] | [bigint],
}
export interface UserProfile {
  'id' : Principal,
  'bio' : string,
  'username' : string,
  'displayName' : string,
  'socialLinks' : Array<string>,
  'followersCount' : bigint,
  'createdAt' : bigint,
  'avatarUrl' : string,
  'isBanned' : boolean,
  'isAdmin' : boolean,
  'followingCount' : bigint,
  'coverUrl' : string,
  'skills' : Array<string>,
  'postsCount' : bigint,
}
export interface _SERVICE {
  'addComment' : ActorMethod<[bigint, string], bigint>,
  'adminDeletePost' : ActorMethod<[bigint], boolean>,
  'banUser' : ActorMethod<[Principal], boolean>,
  'chatWithAI' : ActorMethod<
    [string, Array<{ 'content' : string, 'role' : string }>],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'clearMyOpenAIApiKey' : ActorMethod<
    [],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'createConversation' : ActorMethod<
    [Array<Principal>, boolean, string],
    bigint
  >,
  'createPost' : ActorMethod<
    [string, Array<string>, string, Array<string>, boolean, [] | [bigint]],
    bigint
  >,
  'deleteComment' : ActorMethod<[bigint], boolean>,
  'deletePost' : ActorMethod<[bigint], boolean>,
  'followUser' : ActorMethod<[Principal], boolean>,
  'generateCaption' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'getAdminPosts' : ActorMethod<[bigint, bigint], Array<Post>>,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getAdminUsers' : ActorMethod<[bigint, bigint], Array<UserProfile>>,
  'getComments' : ActorMethod<[bigint], Array<Comment>>,
  'getConversations' : ActorMethod<[], Array<Conversation>>,
  'getExplorePosts' : ActorMethod<[bigint, bigint], Array<Post>>,
  'getFeedPosts' : ActorMethod<[bigint, bigint], Array<Post>>,
  'getFollowers' : ActorMethod<[Principal], Array<UserProfile>>,
  'getFollowing' : ActorMethod<[Principal], Array<UserProfile>>,
  'getMessages' : ActorMethod<[bigint, bigint, bigint], Array<Message>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getPost' : ActorMethod<[bigint], [] | [Post]>,
  'getProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getReels' : ActorMethod<[bigint, bigint], Array<Post>>,
  'getSavedPosts' : ActorMethod<[], Array<Post>>,
  'getSuggestedUsers' : ActorMethod<[], Array<UserProfile>>,
  'getTrendingHashtags' : ActorMethod<[], Array<[string, bigint]>>,
  'getUnreadNotificationCount' : ActorMethod<[], bigint>,
  'getUserPosts' : ActorMethod<[Principal, bigint, bigint], Array<Post>>,
  'isFollowingUser' : ActorMethod<[Principal], boolean>,
  'isMyOpenAIConfigured' : ActorMethod<[], boolean>,
  'isPostLiked' : ActorMethod<[bigint], boolean>,
  'likeComment' : ActorMethod<[bigint], boolean>,
  'likePost' : ActorMethod<[bigint], boolean>,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  'markMessageRead' : ActorMethod<[bigint], boolean>,
  'markNotificationRead' : ActorMethod<[bigint], boolean>,
  'registerUser' : ActorMethod<[string, string], boolean>,
  'reportContent' : ActorMethod<[string, string, string], bigint>,
  'savePost' : ActorMethod<[bigint], boolean>,
  'searchUsers' : ActorMethod<[string], Array<UserProfile>>,
  'sendMessage' : ActorMethod<[bigint, string], bigint>,
  'setMyOpenAIApiKey' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'suggestHashtags' : ActorMethod<
    [string],
    { 'ok' : Array<string> } |
      { 'err' : string }
  >,
  'unbanUser' : ActorMethod<[Principal], boolean>,
  'unfollowUser' : ActorMethod<[Principal], boolean>,
  'unlikePost' : ActorMethod<[bigint], boolean>,
  'unsavePost' : ActorMethod<[bigint], boolean>,
  'updateProfile' : ActorMethod<
    [string, string, string, string, Array<string>, Array<string>],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];